name: デプロイ

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Clasp
        run: |
          npm init -y
          npm install clasp -g

      - name: Create clasprc.json
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo $CLASPRC_JSON > ~/.clasprc.json

      # clasp push実行
      # 1.標準出力と標準エラー出力を両方とも同一ファイルに出力（直接変数に出力すると改行されなくなるため）
      # 2.ファイル内容を変数にセット
      # 3.変数の改行を除去（$GITHUB_ENVにセットするときにエラーになるため）
      # 4.$GITHUB_ENVにセット
      - name: Clasp push
        run: |
          RESULT=`clasp push -f 2>&1 | tee ~/result.log`
          # RESULT=`cat ~/result.log`
          echo -e $RESULT
          RESULT=`echo $RESULT | sed -e "s/[\r\n]\+//g"`
          echo "result=$RESULT" >> $GITHUB_ENV

      # clasp pushが失敗した場合にjobをエラー終了させるためのstep
      - name: Failure action
        # コマンド結果に「Push failed」が含まれていたら失敗したと判断
        if: ${{ contains(env.result, 'Push failed') || startsWith(env.result, 'Error retrieving') }}
        run: |
          cat ~/result.log
          exit 1
