name: デプロイ

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Clasp
        run: |
          npm init -y
          npm install clasp -g

      - name: Create clasprc.json
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo $CLASPRC_JSON > ~/.clasprc.json

      # clasp push実行＆結果を$GITHUB_ENVにセット
      - name: Clasp push
        run: |
          clasp push -f 1> stdout.log 2> stderr.log

      # clasp pushの結果が失敗ならエラー終了する
      - name: Judge failure
        run: |
          echo "=(1)=============="
          cat stdout.log | wc -l
          echo "==============="
          echo "=(2)=============="
          cat stderr.log | wc -l
          echo "==============="
