name: デプロイ

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Clasp
        run: |
          npm init -y
          npm install clasp -g

      - name: Create clasprc.json
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo $CLASPRC_JSON > ~/.clasprc.json

      # clasp push実行（結果を$GITHUB_ENVにセット）
      - name: Clasp push
        run: |
          clasp push -f > result.log 2>&1
          RESULT=`cat result.log`
          RESULT=`echo $RESULT | sed -e "s/[\r\n]\+//g"`
          echo "result=$RESULT" >> $GITHUB_ENV

      # clasp pushが失敗した場合にjobをエラー終了させるためのstep
      - name: Failure action
        # コマンド結果に「Push failed」が含まれていたら失敗したと判断
        if: ${{ contains(env.result, 'Push failed') }}
        run: |
          cat result.log
          exit 1
