name: デプロイ

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Clasp
        run: |
          npm init -y
          npm install clasp -g

      - name: Create clasprc.json
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo $CLASPRC_JSON > ~/.clasprc.json

      - name: Clasp push
        run: |
          # clasp push実行＆結果を変数にセット
          OUTPUT=$(clasp push -f)
          # 改行を除去
          OUTPUT=`echo ${OUTPUT} | sed -e "s/[\r\n]\+//g"`
          # resultというキーでclasp pushの結果をセット
          echo "result=$OUTPUT" >> $GITHUB_ENV

      - name: Judge success or failure
        run: |
          # clasp pushの結果を取得
          echo "env-value is ${{ env.result }}"
