name: デプロイ

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Clasp
        run: |
          npm init -y
          npm install clasp -g

      - name: Create clasprc.json
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo $CLASPRC_JSON > ~/.clasprc.json

      - name: Deploy
        run: |
          OUTPUT="└─ src/appsscript.json └─ src/main.js Pushed 2 files."
          echo "=============="
          echo $OUTPUT
          echo "=============="
          echo "deploy-output='$OUTPUT'" >> $GITHUB_ENV

      - name: use env-value
        run: |
          echo "env-value is ${{ env.deploy-output }}"
